# docker-compose.yml
version: '3.8'

services:
  bot:
    image: kixyu9527/tg_pm_bot:latest
    platform: linux/amd64
    container_name: telegram_bot
    env_file:
      - 1panel.env
    ports:
      - "9527:9527"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: telegram_mysql
    env_file:
      - 1panel.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: