services:
  bot:
    build: .
    container_name: telegram_bot
    env_file: .env
    ports:
      - "9527:9527"
    depends_on:
      - mysql
    volumes:
      - .:/app
    restart: always

  mysql:
    image: mysql:8.0
    container_name: telegram_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: