services:
  bot:
    image: kixyu9527/tg_pm_bot:latest
    container_name: telegram_bot
    network_mode: host
    env_file:
      - 1panel.env
    environment:
      DB_HOST: 127.0.0.1
      TZ: Asia/Shanghai
    restart: always
